name: flaska
base: core22
version: '0.1'
summary: Python flask app
description: |
  Example Python Flask app

grade: stable
confinement: strict

parts:
  main:
    plugin: python
    source: .
    stage-packages:
      - curl

apps:
  flaska:
    command: bin/flaska
    daemon: simple
    plugs: [network-bind]

hooks:
  check-health:
    plugs: [network]
